### PR TITLE
Fix build options for power images

### PR DESCRIPTION
**Pull request by mkumatag**
Fixes: https://github.com/gliderlabs/docker-alpine/issues/413

### CODE REVIEW

**Comment by mkumatag** [comment]
@ncopa I see following error in the circle ci:

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/ppc64le/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: UNTRUSTED signature
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/ppc64le/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: UNTRUSTED signature
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  alpine-baselayout (missing):
    required by: world[alpine-baselayout]
  alpine-keys (missing):
    required by: world[alpine-keys]
  apk-tools (missing):
    required by: world[apk-tools]
  busybox (missing):
    required by: world[busybox]
  libc-utils (missing):
    required by: world[libc-utils]
Exited with code 1
```

any idea why "UNTRUSTED signature" for these repos?

**Comment by ncopa** [comment]
So you didn't test build it before create the PR.

The build server for ppc64le has different signing key than the x86_64, due to there are different people who has (physical) access to those servers (and with that access to the private keys).

The public key is available in `/usr/share/apk/keys/ppc64le`.

Be aware that apk cannot run the pre/post-install scripts or trigger scripts when installed this way, which is the main reason why we generate the minirootfs images in the first place.

**Comment by mkumatag** [comment]
> So you didn't test build it before create the PR.
> 
> The build server for ppc64le has different signing key than the x86_64, due to there are different people who has (physical) access to those servers (and with that access to the private keys).
> 

What should be the solution for this? can we use a same key as x86_64 or can we skip checking gpg key while building the image in this case as workaround.?

> The public key is available in /usr/share/apk/keys/ppc64le.
> 
> Be aware that apk cannot run the pre/post-install scripts or trigger scripts when installed this way, which is the main reason why we generate the minirootfs images in the first place.

**Comment by ncopa** [comment]
Building the ppc64le image same way as x86_64 and x86 will not work, due to we need execute the busybox trigger (`busybox --install -s`) to generate the symlinks. This will not work if we build ppc64le image on x86_64 hardware. It works for x86.

So the only way to fix this is to build new rootfs tarball on native hardware. The circle CI way to build images does not support that AFAIK, and i don't think travis supports it either.

I think we need generate new minirootfs tarball in upstream Alpine.

**Comment by mkumatag** [comment]
> So the only way to fix this is to build new rootfs tarball on native hardware. The circle CI way to build images does not support that AFAIK, and i don't think travis supports it either.

@ncopa we do have a support in travis now, you can use `linux-ppc64le` as os type or you can use in the matrix as well

example: 
https://github.com/shenki/skiboot-debian/blob/e05f129c327815675f717ab9d998386e0939c485/.travis.yml#L5
https://github.com/grooverdan/travis-test/blob/401f0e52d23cff7f3380ec1a5f11929d12a5541d/.travis.yml#L5

**Comment by mkumatag** [comment]
@ncopa any updates? were you able to use Travis for ppc64le architecture?

**Comment by ncopa** [comment]
I haven't replaced the current circleci with travis. We also need armhf, aarch64 and s390x support, so I will likely not change to travis anything soon.

I did tag new alpine releases and made new alpine images for all supported arches. So ppc64le images should be updated now.

**Pull request merged**
