### PR TITLE
Disable root password to prevent su

### LINKED ISSUE #101: Su from normal user to root without password - easy privilege escalation?
Currently root/su is configured on gliderlabs/alpine that su from normal user to root is possible without providing any password (just writing "su" and pressing Enter). I find that default bit problematic as any service should run as normal user and not root, but currently there is no gain in that. If attacker is able to gain normal user - he can easily escalate its privileges. Therefore, I think default should be more secure.

### PR DESCRIPTION
**Pull request by andyshinn**
Closes #101 #107.

### CODE REVIEW

**Comment by frol** [comment]
Looks good to me, though you could simplify the tests using any of the existing users:

```bash
docker run --user nobody alpine:3.2 su
```

**Comment by frol** [comment]
What is the showstopper here?

**Comment by andyshinn** [comment]
This is in the `gliderlabs/alpine` images now. I'm working through some build script fixes to properly push the official branches and will get a PR open for them in a day or two.

**Comment by frol** [comment]
@andyshinn Thank you!

**Comment by frol** [comment]
@andyshinn I'm sorry to disturb you again, but have you had a chance to fix the issue for the official Alpine image?

**Comment by andyshinn** [comment]
I'm working on fixing up the building and committing of official tarballs before I can properly do that. Follow #94.

**Comment by andyshinn** [comment]
Downstream PR https://github.com/docker-library/official-images/pull/1292

**Comment by frol** [comment]
@andyshinn Thank you for keeping us up-to-date!

**Pull request merged**
