### PR TITLE
Add ImageLayers badge

### PR DESCRIPTION
**Pull request by moul**
Here is another URL with all the current tags:
https://imagelayers.io/?images=gliderlabs%2Falpine:latest,gliderlabs%2Falpine:edge,gliderlabs%2Falpine:3.2,gliderlabs%2Falpine:3.1,gliderlabs%2Falpine:2.7,gliderlabs%2Falpine:2.6

### CODE REVIEW

**Comment by andyshinn** [comment]
Hmm. Do they have a shields.io badge? Neat service. But the image look isn't consistent with the other badges :disappointed:

**Comment by moul** [comment]
@andyshinn I think they don't :/

**Comment by andyshinn** [comment]
Maybe I'll look into what it takes to add it to shields.io. But can you amend your commit to also add the link to `docs/index.md` so I can merge?

**Comment by moul** [comment]
sure, done

**Comment by andyshinn** [comment]
I was playing a bit with ImageLayers and it looks like they do have a simple API exposed that could be used by shields.io:

```console
$ curl -sSL -H 'Content-Type: application/json' -X POST -d '{"repos": [{"name": "gliderlabs/alpine", "tag": "latest"}]}' "https://imagelayers.io:8888/registry/analyze" | jq '.[].repo'
{
  "name": "gliderlabs/alpine",
  "tag": "latest",
  "size": 5245116,
  "count": 1
}
```

I'm going to first see if I can work up a pull request to them.

**Comment by andyshinn** [comment]
We'll see if https://github.com/badges/shields/pull/538 gets accepted. If so, you can modify to use Shields.io.

**Comment by andyshinn** [comment]
https://github.com/badges/shields/pull/538 is merged if you want to change this to use the two new images for `image-size` and `layers`.

**Comment by moul** [comment]
I don't think badges/shields#538 was released in production, however, my update should works

**Comment by andyshinn** [comment]
The tag is missing from the image. Should be `<image>/<tag>.<format>`.

**Comment by moul** [comment]
Yup thanks, fixed

**Pull request merged**
