### PR TITLE
Bump 3.4 VERSION_ID tests to 3.4.1

### LINKED ISSUE #198: Alpine 3.4.1
Alpine 3.4.1 is out. Just wondering if you can update and release new gliderlabs and alpine images for it.

Also, I'm curious if you guys could support semantic versioning in releases, somewhat similar to what docker images like golang or ubuntu are doing.

ie: 
alpine:3  (would be 3.4.1 under the hood right now)
alpine:3.4  (would be 3.4.1 under the hood right now)
alpine:3.4.0
alpine:3.4.1
alpine:3.3
alpine:3.3.3
etc

### PR DESCRIPTION
**Pull request by tianon**
Closes #198

Noticed this when the tests on #199 failed :smile:

### CODE REVIEW

**Comment by tianon** [comment]
Trying to figure out what's up with `edge` that's causing it to fail on this (or what value it's got for `VERSION_ID` atm if not 3.4.1). :confused:

**Comment by tianon** [comment]
Turns out `edge` is still set to `VERSION_ID=3.4.0` :smile:

**Comment by MindTooth** [comment]
http://alpinelinux.org/posts/Alpine-3.4.3-released.html

👍

**Comment by tianon** [comment]
Updated for 3.4.3 :+1:

**Comment by tianon** [comment]
df663535dfe8585b5f86e637fad1a4b7bdc39f51 :+1:

**Comment by tianon** [comment]
(although it would appear that the tests already need a bump to 3.4.4 :innocent:)

**Pull request closed without merging**
