### PR TITLE
Use global CDN for package installation

### PR DESCRIPTION
**Pull request by andyshinn**
This is open for feedback and testing. We had reports that package installation was very slow (the default mirror is set to one in the US). This adds a CDN endpoint `alpine.gliderlabs.com` which caches `nl.alpinelinux.org`. The Alpine Linux package index uses ETags which CloudFront obeys to invalidate cache, so updates should get picked up fairly quickly.

Speed in regions other than the US should be improved once packages are fetched and cached the first time. However, there are two concerns:

* Costs supporting the CloudFront distribution. I have no idea of potential load and cost of the CloudFront distribution. Though, we are happy to sponsor the costs if it ends up being reasonable.
* It is not an official means of repository usage and may differ too much from upstream.

To test this out, you can load up one of the images from the [CircleCI build artifacts](https://circleci.com/gh/gliderlabs/docker-alpine/45):

```
curl -s https://circle-artifacts.com/gh/gliderlabs/docker-alpine/45/artifacts/3/home/ubuntu/docker-alpine/images/gliderlabs_alpine_3.1_build-45.tar.gz | docker load
```

### CODE REVIEW

**Comment by luislavena** [comment]
@andyshinn an alternative will be CloudFlare with the free plan (which offers CDN) but that requires:

- DNS to be managed by CloudFlare (not *bad* actually)
- Alpine Linux mirror server needs to support the new *Host*

If you guys figure this out, let me know :smile:

**Comment by andyshinn** [comment]
Yea, we did look at CloudFlare as well. But it seemed like it might be too much involvement upstream to do DNS hackery. I do want to solve the "mirror too far away" problem and am still playing with ideas.

**Comment by thaJeztah** [comment]
Have you tried reaching out to CloudFlare or (e.g.) DigitalOcean? Perhaps they are willing to sponsor in exchange for some exposure

**Comment by mgood** [comment]
Yeah, I tried pointing CloudFlare at some existing mirrors which fails since they have virtual hosts and don't recognize the custom domain. However, you could point CloudFlare at the `alpine.gliderlabs.com` mirror. CloudFlare does seem supportive of open source, so they might be open to something. There's also Fastly who is currently donating their CDN services to the Python Package Index.

**Comment by sgoblin** [comment]
MaxCDN also sponsors some open source things: https://www.maxcdn.com/open-source/

**Comment by tilgovi** [comment]
I'm :+1: for figuring out something because I've been trying to build images all day and failing due to temporary problems with the default mirror. I tried adding other mirrors but unfortunately apk doesn't seem to fall back when there are problems. :-/

**Comment by andyshinn** [comment]
Fastly was the only CDN to actually be very open to the idea. I've merged this in for the `gliderlabs/alpine` image only at the moment. It may also make its way to the official Alpine image. But for the moment, this will be one differentiating feature between the two.

I'll be pushing this out to Docker Hub today or tomorrow.

**Comment by thaJeztah** [comment]
Thanks, and thanks @fastly!!

**Pull request merged**
