### PR TITLE
Fix #121: Added missing busybox-suid package to Alpine 3.3 and edge

### LINKED ISSUE #121: [Alpine 3.3 regression] Missing busybox-suid package
`busybox-suid` package provides correctly working `/usr/bin/su` (`/bin/su` exists, but since `/bin/busybox` doesn't have suid bit, it just doesn't work for regular users (`su: must be suid to work properly`)), `/usr/bin/passwd`, `/usr/bin/crontab`, and `/usr/bin/traceroute`.

/cc @andyshinn

### PR DESCRIPTION
**Pull request by frol**
More details are available in the issue #121.

### CODE REVIEW

**Comment by jumanjiman** [comment]
imho it's better to *not* include bbox-suid in the base image.
if it's in the base image, then i just have to remove it, and
that makes the resulting image larger via layers.

if somebody needs it, the person can add it to their docker image.

there is a discussion beginning at http://lists.alpinelinux.org/alpine-aports/1881.html
in which it was proposed...

> If alpine is run as a chroot or docker container or likewise installation , which is no longer uncommon these days, having suid binaries included in installation should no longer be required and is imo quite undesirable if you think about security. 

the patch to split the packages is at
http://lists.alpinelinux.org/alpine-aports/1809.html

**Comment by andyshinn** [comment]
The original issue was of privilege escalation from a non-root user. What would be the test to solve this issue?

**Comment by frol** [comment]
@jumanjiman What are the security issues about this particular `bbsuid` file? I'm especially interested to here what it can cause in Docker. From my perspective, in this particular case it is completely secure, it has `---s--x--x` permissions, so nobody, but root can even read it. If you give a Docker container to run as root, having this small `bbsuid` binary (9944 bytes, BTW), won't make any difference. On the other hand, if you give a regular user access, the user won't make more harm than on a standalone Alpine Linux (if, for example, there would be a vulnerability in the code of `bbsuid`), thus it must be patched anyway.

`busybox-suid` package adds only 0.028MB to the total size of the image:

```
alpine-bbsuid      latest             014f8d3149c7        6 seconds ago       4.822 MB
alpine             3.3                74e49af2062e        34 hours ago        4.794 MB
```

I might agree on not adding `busybox-suid` to the base image (though, I have a little vote here) if there would be added a good documentation of this "feature", and, ideally, the error message ("su: must be suid to work properly"), running `su`, should be also improved to something pointing to `busybox-suid` package (since its name is not so obvious when you hit the issue running `su` command).

Nevertheless, I'm still interested in the real-life examples where `bbsuid` must be avoided.

Thus, on the one hand, we have good user experience (no regression upgrading from 3.2) + 0.028MB increase of the base image size, and on the other hand, we introduce a regression in the behaviour on upgrade from 3.2 to 3.3 because of a fear of an unknown (at least to me) vulnerability.

**Comment by jumanjiman** [comment]
> The original issue was of privilege escalation from a non-root user. There is a test for it which does pass on edge and 3.3 with the newer patched BusyBox (the original patch was incomplete and it was fixed before 3.3 release). What would be the test to solve this as a separate issue?

to me, the inclusion of bbsuid is completely separate from https://github.com/gliderlabs/docker-alpine/issues/101

**Comment by jumanjiman** [comment]
> If you are adding users to the image with a RUN command I would think it wouldn't be too much overhead to just compound apk --no-cache add busybox-suid to that command.

agree 100%

**Comment by jumanjiman** [comment]
> ideally, the error message ("su: must be suid to work properly"), running su, should be also improved to something pointing to busybox-suid package (since its name is not so obvious when you hit the issue running su command).

the potential breakage in usability was ack'd in the upstream alpine thread.

**Comment by jumanjiman** [comment]
should bbsuid be in the base image?

it's a question that has many subtle answers.

if we boil it down to simplicity and economics, i would argue that it's easier to add bbsuid for the rare instance when one actually needs it than to remove bbsuid in the vast majority of cases where bbsuid is not needed for an app.

it's also important for compliance in regulated industries, especially with the abundance of breaches and corresponding attention to audits and compliance.

auditors *always* ask for a list of suid binaries in every deployment, and they follow that up with questions about the need for those bins. from the perspective of simplicity, it's easy to describe that we simply do not have suid binaries in our images. then we can focus on the unusual cases where suid *is* needed, and we can document in version control *why* the suid is necessary.

**Comment by jumanjiman** [comment]
there is another aspect, too. it involves the conversation with junior devs and mgmt around security audits of new container images.

"why should we remove that package? if it weren't important, it wouldn't be part of the base image."

it's much more informative to have a discussion with somebody about how bbsuid enables a functionality that their app requires, rather than have friction about why they don't need bbsuid. (it's easier for somebody to understand how something explicitly helps them, as opposed to talking about ghostly potential vulnerabilities.)

**Comment by frol** [comment]
I'm fine with installing busybox-suid myself. Hopefully, those who will bump into the issue will quickly find this thread and will know that they need to install busybox-suid themselves.

**Comment by jumanjiman** [comment]
> Hopefully, those who will bump into the issue will quickly find this thread and will know that they need to install busybox-suid themselves.

ack, and thanks for opening the issue.
it helps to establish the conversation.

**Pull request closed without merging**
