### PR TITLE
Self-hosted builder

### PR DESCRIPTION
**Pull request by muhmuhten**
Sorry for the new pull request, I had a Rebase Accident™ trying to reword the `-b` commit.

### CODE REVIEW

**Comment by andyshinn** [comment]
Can we squash all these commit into one? I'm ready to merge this in to master and start trying it out. Everything seems to be working as far as I can tell. I guess I should start adding some tests to the builder to easily see that all the options are working.

**Comment by muhmuhten** [comment]
I suppose? is there any particular reason to discard the history here?

**Comment by andyshinn** [comment]
Usually to keep features as single commits, especially when the history is more figuring out the feature and non-additive. But not necessary.

**Comment by muhmuhten** [comment]
in that case, I'd rather have split this into two commits, one for the self-hosting and another for the -p behaviour. At this point that would be messy, though, since the feature implementation is interspersed with bugfix.

**Comment by andyshinn** [comment]
Yep, that is a much better squash of commits. Let's do that and get this merged in! If it breaks something it will be a good case for some more tests.

**Comment by muhmuhten** [comment]
I did what squashing I could get git to do automatically #76

**Pull request closed without merging**
