### PR TITLE
Remove 2.x images

### PR DESCRIPTION
**Pull request by ncopa**
alpine 2.6 and 2.7 are no longer supported upstream.

### CODE REVIEW

**Comment by andyshinn** [comment]
I've never used the 2.x image and I'm not sure any others do. But I'd like to first grab some statistics for the 2.x tags from Docker Hub before just pulling them out from under people that could be using them. Maybe it is worth starting out with some sort of end-of-life / deprecation notice?

**Comment by moul** [comment]
I only use the latest/edge images

**Comment by andyshinn** [comment]
I'm gathering some log data for the 2.x images. For the official images it seems safe to remove as they will keep the old tags around for some time anyways. We can probably safely merge this and kill the 2.x images in a month or so.

**Comment by andyshinn** [comment]
Per the official internal stats from Docker:

> "2.7" is about 1.5% of pulls and "2.6" is about 0.5%.

Good enough for me. Bye bye 2.x, hardly knew ye!

**Pull request merged**
